#!/bin/bash

sudo rm /etc/systemd/system/scale.service 
sudp cp scale.service /etc/systemd/system/scale.service
sudo systemctl daemon-reload
sudo systemctl enable scale.service
sudo systemctl start scale.service
sudo systemctl status scale.service